// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7dhJv0uBLb8iQXA-5qMmk46S-cFDisZk',
    appId: '1:863182203504:web:bfeb8ad86005cf3d1fe2b5',
    messagingSenderId: '863182203504',
    projectId: 'mentalzen-932af',
    authDomain: 'mentalzen-932af.firebaseapp.com',
    storageBucket: 'mentalzen-932af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBojHU9UIs0enhklT8Sg-wDqsMX9w_1Shg',
    appId: '1:863182203504:android:5e9c3bb80a5d6b751fe2b5',
    messagingSenderId: '863182203504',
    projectId: 'mentalzen-932af',
    storageBucket: 'mentalzen-932af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkNZF6EQYJV09EC7VBVgj0sUB7ztMDJZs',
    appId: '1:863182203504:ios:2ba7894c8216e56c1fe2b5',
    messagingSenderId: '863182203504',
    projectId: 'mentalzen-932af',
    storageBucket: 'mentalzen-932af.firebasestorage.app',
    iosBundleId: 'com.example.mentalZen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkNZF6EQYJV09EC7VBVgj0sUB7ztMDJZs',
    appId: '1:863182203504:ios:2ba7894c8216e56c1fe2b5',
    messagingSenderId: '863182203504',
    projectId: 'mentalzen-932af',
    storageBucket: 'mentalzen-932af.firebasestorage.app',
    iosBundleId: 'com.example.mentalZen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7dhJv0uBLb8iQXA-5qMmk46S-cFDisZk',
    appId: '1:863182203504:web:f5d489e6f388f01b1fe2b5',
    messagingSenderId: '863182203504',
    projectId: 'mentalzen-932af',
    authDomain: 'mentalzen-932af.firebaseapp.com',
    storageBucket: 'mentalzen-932af.firebasestorage.app',
  );
}
